-- Migration to create admissions table with unique 6-digit student_id

CREATE TABLE IF NOT EXISTS public.admissions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id varchar(6) UNIQUE NOT NULL,
  student_name text NOT NULL,
  date_of_birth date NOT NULL,
  gender text NOT NULL,
  blood_group text,
  religion text,
  caste text,
  nationality text NOT NULL,
  mother_tongue text,
  aadhar_number text,
  father_name text NOT NULL,
  father_occupation text,
  father_qualification text,
  father_phone text NOT NULL,
  father_email text,
  father_income numeric,
  mother_name text NOT NULL,
  mother_occupation text,
  mother_qualification text,
  mother_phone text NOT NULL,
  mother_email text,
  mother_income numeric,
  guardian_name text,
  guardian_relation text,
  guardian_phone text,
  guardian_email text,
  permanent_address text NOT NULL,
  permanent_city text NOT NULL,
  permanent_state text NOT NULL,
  permanent_pincode text NOT NULL,
  current_address text NOT NULL,
  current_city text NOT NULL,
  current_state text NOT NULL,
  current_pincode text NOT NULL,
  previous_school text,
  previous_class text,
  previous_percentage numeric,
  admission_class text NOT NULL,
  transport_required boolean,
  medical_conditions text,
  special_requirements text,
  extracurricular text,
  emergency_contact text,
  emergency_phone text,
  birth_certificate_url text,
  transfer_certificate_url text,
  marksheet_url text,
  passport_photo_url text,
  aadhar_card_url text,
  address_proof_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Index on student_id for quick lookup
CREATE UNIQUE INDEX IF NOT EXISTS idx_admissions_student_id ON public.admissions(student_id);
